[build]
builder = "nixpacks"

[deploy]
startCommand = "node --max-old-space-size=460 --optimize-for-size --expose-gc index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
region = "europe-west4"

[deploy.healthcheck]
path = "/health"
intervalSeconds = 30
timeoutSeconds = 10
